import { Show } from "../video-player/show.model";

export const mockShows: Show[] = [
  // {
  //   lastUpdate: new Date(2018, 10, 1),
  //   name: 'Gintama',
  //   numSeasons: 2,
  //   numEps: 48,
  //   state: 'finished',
  //   thumImgUrl: 'assets/gintama.jpg',
  //   bannerImgUrl: 'assets/banner/gintama.jpg',
  //   id: '1',
  // },
  // {
  //   lastUpdate: new Date(2018, 10, 2),
  //   name: 'Kaguya-sama: Love Is War',
  //   numSeasons: 2,
  //   numEps: 15,
  //   state: 'onGoing',
  //   thumImgUrl: 'assets/kaguyasama.jpg',
  //   bannerImgUrl: 'assets/banner/kaguyasama.jpg',
  //   id: '2',
  // },
  // {
  //   lastUpdate: new Date(2018, 10, 3),
  //   name: 'Kill La Kill',
  //   numSeasons: 1,
  //   numEps: 26,
  //   state: 'finished',
  //   thumImgUrl: 'assets/kill-la-kill.jpg',
  //   id: '2',
  // },
  // {
  //   lastUpdate: new Date(2018, 10, 4),
  //   name: 'Kitsume No Yaiba',
  //   numSeasons: 1,
  //   numEps: 26,
  //   state: 'onGoing',
  //   thumImgUrl: 'assets/kitsume-no-yaiba.jpg',
  //   id: '2',
  // },
  // {
  //   lastUpdate: new Date(2018, 10, 5),
  //   name: 'Re:Zero − Starting Life in Another World',
  //   numSeasons: 1,
  //   numEps: 26,
  //   state: 'onGoing',
  //   thumImgUrl: 'assets/re-zero.jpg',
  //   id: '2',
  // },
  // {
  //   lastUpdate: new Date(2018, 10, 6),
  //   name: 'Sword Art Online',
  //   numSeasons: 4,
  //   numEps: 60,
  //   state: 'onGoing',
  //   thumImgUrl: 'assets/sao.jpg',
  //   id: '2',
  // },
  // {
  //   lastUpdate: new Date(2018, 10, 7),
  //   name: 'Steins;Gate',
  //   numSeasons: 2,
  //   numEps: 48,
  //   state: 'finished',
  //   thumImgUrl: 'assets/steins-gate.jpg',
  //   id: '2',
  // },
  // {
  //   lastUpdate: new Date(2018, 10, 8),
  //   name: 'The Promised Neverland',
  //   numSeasons: 1,
  //   numEps: 13,
  //   state: 'finished',
  //   thumImgUrl: 'assets/the-promised-neverland.jpg',
  //   id: '2',
  // },
];
